#!/usr/bin/env node
/**
 * Generate functions/lib/entry.js, the entrypoint named by package.json#main.
 *
 * Deployment config in this repo is plain environment variables (Replit
 * Secrets, CI variables, an `export` in a shell) -- there are no .env files
 * and no per-project config files. That works everywhere except inside the
 * processes firebase-tools spawns for us: function discovery, the emulated
 * runtime and the deployed runtime get an environment firebase-tools builds
 * from scratch (spawnFunctionsProcess() in
 * firebase-tools/lib/deploy/functions/runtimes/node/index.js), namely
 * FIREBASE_CONFIG, GCLOUD_PROJECT, GOOGLE_CLOUD_QUOTA_PROJECT, PORT,
 * FUNCTIONS_CONTROL_API, HOME and PATH. Nothing the deploy shell exports
 * survives, and .env files do not reach discovery either (firebase-tools
 * loads them only after discovery, as deployed runtime env).
 *
 * The build, however, DOES run in the deploy shell -- firebase.json runs it as
 * the functions predeploy hook -- so this is the one place that can see the
 * environment and hand it on. It reads the config variables below and stamps
 * them into the generated entrypoint, which sets them on process.env before
 * requiring any application code. Same idea as Vite baking VITE_ vars into the
 * frontend bundle: ordinary env vars in, a self-contained build out.
 *
 * A variable that is genuinely present in the environment at run time always
 * wins over the stamped value, and a variable missing at build time is simply
 * not stamped -- the code that needs it then throws loudly at load, which is
 * the required behaviour for region (see src/config/region.ts).
 */
import { existsSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

/**
 * Deployment config carried from the build environment into the runtime.
 * Add a name here and it is available as process.env.<name> everywhere this
 * codebase runs; nothing else needs to change.
 */
const CONFIG_VARS = ["VITE_FIREBASE_FUNCTIONS_REGION"]

/** Compiled index, relative to lib/ (tsconfig roots at the repo, not src/). */
const COMPILED_INDEX = "./functions/src/index.js"

const functionsDir = dirname(dirname(fileURLToPath(import.meta.url)))
const libDir = join(functionsDir, "lib")
const entryPath = join(libDir, "entry.js")

if (!existsSync(join(libDir, COMPILED_INDEX))) {
  console.error(
    `build-entry: ${join(libDir, COMPILED_INDEX)} is missing -- run tsc first ` +
      "(npm run build does both)."
  )
  process.exit(1)
}

const stamped = []
const missing = []
for (const name of CONFIG_VARS) {
  const value = process.env[name]
  if (value === undefined || value === "") missing.push(name)
  else stamped.push([name, value])
}

const entry = [
  "// GENERATED by tools/build-entry.mjs. Do not edit; do not commit.",
  "//",
  "// firebase-tools spawns function discovery, the emulators and the deployed",
  "// runtime with an environment of its own making, so nothing the deploy",
  "// shell exported reaches them. These assignments carry the deployment",
  "// config the build could see; a real environment variable still wins.",
  ...stamped.map(
    ([name, value]) =>
      `if (!process.env[${JSON.stringify(name)}]) ` +
      `process.env[${JSON.stringify(name)}] = ${JSON.stringify(value)};`
  ),
  `module.exports = require(${JSON.stringify(COMPILED_INDEX)});`,
  "",
].join("\n")

writeFileSync(entryPath, entry)

const describe = (names) => (names.length ? names.join(", ") : "none")
console.log(
  `build-entry: wrote lib/entry.js (from environment: ` +
    `${describe(stamped.map(([name]) => name))}; not set: ${describe(missing)})`
)
